name: newsapp
description: "News App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.3.15
  retrofit: ^4.4.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
